net-splitcells-os-state-interface-test:
  when: manual # Disabled in order to not waste resources of GitLab, as CI runs on other platforms already.
  image: python:3.7
  script:
    - cd projects/net.splitcells.system.root
    - ./bin/build.part.with.python
test:
  when: manual # Disabled in order to not waste resources of GitLab, as CI runs on other platforms already.
  image: maven:3.6.3-openjdk-11
  script:
    - cd ..
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/splitcells-net/net.splitcells.network.bom.git
    - cd net.splitcells.network.bom
    - mvn clean install
    - cd ../net.splitcells.network/projects/net.splitcells.system.root
    - ./bin/build.part.with.java