# SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
# SPDX-FileCopyrightText: Contributors To The `net.splitcells.*` Projects
baseURL = "https://splitcells-net.srht.site/"
languageCode = "en-us"
title = "Splitcells Network Blog"
theme = "HugoTeX"

[outputs]
section = ["HTML", "RSS"]
