name: Continous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        language: [ 'java']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: 'jdk'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/..
          git clone git@github.com:www-splitcells-net/net.splitcells.network.bom.git
          cd net.splitcells.network.bom
          mvn install
          cd $GITHUB_WORKSPACE/projects/net.splitcells.system.root
          echo $GITHUB_WORKSPACE
          export test_codecov=1
          ./bin/build
          bash <(curl -s https://codecov.io/bash) # Upload tests to codecov.io.